name: Daily Cron Job

on:
  schedule:
    # Runs at midnight UTC time (8am SGT)
    - cron: '0 0 * * *'

jobs:
  run-functions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Specify the Node.js version you need

    - name: Install dependencies
      run: npm install

    - name: Run deployer.mjs
      run: curl -X POST "https://tradetrust-scan.netlify.app/.netlify/functions/deployer"

    - name: Run titleEscrowsCreated.mjs
      run: curl -X POST "https://tradetrust-scan.netlify.app/.netlify/functions/titleEscrowsCreated"
    
    

