name: Daily Cron Job

on:
  schedule:
    # Runs at midnight UTC time (8am SGT)
    - cron: '0 0 * * *'

jobs:
  run-functions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Specify the Node.js version you need

    - name: Install dependencies
      run: npm install

    - name: Run deployer.mjs
      run: curl -X POST "https://tradetrust-scan.netlify.app/.netlify/functions/deployer"

    - name: Run sepolia-titleEscrow.mjs
      run: curl -X POST "https://tradetrust-scan.netlify.app/.netlify/functions/sepolia-titleEscrow"
    

    - name: Run eth-titleEscrow.mjs
      run: curl -X POST "https://tradetrust-scan.netlify.app/.netlify/functions/eth-titleEscrow"
      

    - name: Run gtn-titleEscrow.mjs
      run: curl -X POST "https://tradetrust-scan.netlify.app/.netlify/functions/gtn-titleEscrow"
    

    - name: Run stabilityTestnet-titleEscrow.mjs
      run: curl -X POST "https://tradetrust-scan.netlify.app/.netlify/functions/stabilityTestnet-titleEscrow"


    - name: Run polygon-titleEscrow.mjs
      run: curl -X POST "https://tradetrust-scan.netlify.app/.netlify/functions/polygon-titleEscrow"


    - name: Run amoy-titleEscrow.mjs
      run: curl -X POST "https://tradetrust-scan.netlify.app/.netlify/functions/amoy-titleEscrow"


    - name: Run xdc-titleEscrow.mjs
      run: curl -X POST "https://tradetrust-scan.netlify.app/.netlify/functions/xdc-titleEscrow"


    - name: Run apothem-titleEscrow.mjs
      run: curl -X POST "https://tradetrust-scan.netlify.app/.netlify/functions/apothem-titleEscrow"

    
    

